version: '3.8'

services:
  vibefm:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev 